name: Example
on:
  pull_request:
    branches: [ master ]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Comment with gopher
      uses: BattleBas/action-gophers@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
